// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  author: dynamic(() => import("./Author")),
  blog_post: dynamic(() => import("./BlogPost")),
};
